# Generated by Django 3.0 on 2022-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20220211_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновления'),
        ),
    ]
